services:
  auth-service-db:
    container_name: auth-service-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-service
    ports:
      - 5432:5432
    